// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxlB_s7wzvVrLNBWw86kEZB_byxIGN560',
    appId: '1:1090538031876:web:e8ce0cb6cef808f2135e51',
    messagingSenderId: '1090538031876',
    projectId: 'school-app-8105d',
    authDomain: 'school-app-8105d.firebaseapp.com',
    databaseURL: 'https://school-app-8105d-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-8105d.firebasestorage.app',
    measurementId: 'G-4FNZN5HP5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf_boR4Fd-sK3E6Ekpw221o1pf6N6u3II',
    appId: '1:1090538031876:android:db905a948d06ed33135e51',
    messagingSenderId: '1090538031876',
    projectId: 'school-app-8105d',
    databaseURL: 'https://school-app-8105d-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-8105d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACsKeneyVGB2IGd5AR7tPvTThuz8HATyE',
    appId: '1:1090538031876:ios:fd34bfd26ad14b33135e51',
    messagingSenderId: '1090538031876',
    projectId: 'school-app-8105d',
    databaseURL: 'https://school-app-8105d-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-8105d.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACsKeneyVGB2IGd5AR7tPvTThuz8HATyE',
    appId: '1:1090538031876:ios:fd34bfd26ad14b33135e51',
    messagingSenderId: '1090538031876',
    projectId: 'school-app-8105d',
    databaseURL: 'https://school-app-8105d-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-8105d.firebasestorage.app',
    iosBundleId: 'com.example.projectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxlB_s7wzvVrLNBWw86kEZB_byxIGN560',
    appId: '1:1090538031876:web:262e36fa4e0edc8d135e51',
    messagingSenderId: '1090538031876',
    projectId: 'school-app-8105d',
    authDomain: 'school-app-8105d.firebaseapp.com',
    databaseURL: 'https://school-app-8105d-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-8105d.firebasestorage.app',
    measurementId: 'G-W3KJJPQVNE',
  );
}
